AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'Backend Infrastructure for Cloud Resume'


# ---------- Parameters ----------
Parameters:
  ResumeName:
    Type: String
    Default: mark-cloud-resume
    Description: Enter the name of the S3 Bucket for Cloud Resume    
  DomainName:
    Type: String
    Default: markchentp.com
    Description: Enter the name of a personal domain registered with Route53 Registrar
  CodeBucketName:
    Type: String
    Description: Enter the name of S3 bucket that contains website-counter-lambda.zip 
  FunctionS3VersionID:
    Type: String
    Description: Enter the latest S3 version ID of website-counter-lambda.zip

# ---------- Resources ----------
Resources:
  # Lambda Function for Website Visit
  WebsiteVisitFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${ResumeName}-webVisit-Lambda"
      Runtime: python3.9
      MemorySize: 128   # Mb
      Timeout: 3   # sec
      AutoPublishAlias: prod
      CodeUri:
        Bucket: !Ref CodeBucketName
        Key: website-counter-lambda.zip
        Version: !Ref FunctionS3VersionID
      Handler: lambda_function.lambda_handler
      Policies: 
        - DynamoDBCrudPolicy:
            TableName: !Ref WebsiteVisitTable
      Events:
        WebsiteVisited:
          Type: Api
          Properties:
            RestApiId: !Ref WebsiteVisitAPI
            Path: '/webvisit'
            Method: get

  # API Gateway for Website     
  WebsiteVisitAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "${ResumeName}-API"
      StageName: prod
      EndpointConfiguration: REGIONAL
      OpenApiVersion: 3.0.3
      Cors:
        AllowOrigin: "'https://www.${DomainName}'"
        AllowMethods: "'GET'"
      MethodSettings: 
        - HttpMethod: 'GET'
          ResourcePath: '/webvisit'
          ThrottlingRateLimit: 200
          ThrottlingBurstLimit: 100
        - HttpMethod: 'OPTIONS'
          ResourcePath: '/webvisit'
          ThrottlingRateLimit: 200
          ThrottlingBurstLimit: 100


  # DynamoDB Table for Website Visit     
  WebsiteVisitTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${ResumeName}-webVisit-dynamoDB"
      AttributeDefinitions: 
        - AttributeName: webVisit_count_type
          AttributeType: S
      KeySchema: 
        - AttributeName: webVisit_count_type
          KeyType: HASH     
      ProvisionedThroughput: 
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1


# ---------- Outputs ----------
Outputs:
  APIGatewayInvokeURL:
    Value: !Sub "https://${WebsiteVisitAPI}.execute-api.${AWS::Region}.amazonaws.com/prod/"
    Description: "Invoke URL for WebsiteVisitAPI Prod stage endpoint"