name: Github Actions for Cloud Resume on AWS

on:
  push:
    branches:
    - main
    paths:
      - 'cloud-resume-web/website/*'
      - '.github/workflows/frontend-workflow.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Sync static website contents to S3 bucket
      run: aws s3 sync ./cloud-resume-web/website/ s3://$AWS_S3_BUCKET --follow-symlinks
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_WEBSITE_S3_BUCKET }}

    - name: Invalidate CloudFront Cache
      run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/"
